apiVersion: v2
name: azure-cloud-controller-manager-app
description: A Helm chart for the Azure Cloud Controller Manager.
version: 0.0.1-dev
appVersion: 0.0.1-dev
home: https://github.com/giantswarm/azure-cloud-controller-manager-app
icon: https://s.giantswarm.io/app-icons/azure/1/dark.svg
annotations:
  application.giantswarm.io/team: phoenix
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/azure/1/dark.svg
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
  gpuInstances: false
  compatibleProviders: [azure]
