apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  updateStrategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      priorityClassName: system-node-critical
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      serviceAccountName: {{ .Values.name }}
      hostNetwork: true
      dnsPolicy: Default
      nodeSelector:
        {{-  range $key, $value := $.Values.controller.controlPlaneNodeSelector }}
        {{ $key }}: {{ $value }}
        {{- end}}
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: azure-cloud-controller-manager
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        args:
        - --profiling=false
        - --cloud-config={{ .Values.controller.azureCredentialFile }}
        - --cloud-provider=azure
        {{- if .Values.cluster.calico.CIDR }}
        - --cluster-cidr={{ .Values.cluster.calico.CIDR }}
        {{- end }}
        - --configure-cloud-routes=true
        - --controllers=*,-cloud-node
        - --use-service-account-credentials=true
        - --route-reconciliation-period=10s
        - --leader-elect=true
        {{- if .Values.controller.kubeconfigFromHost }}
        - --kubeconfig=/etc/kubernetes/kubeconfig/controller-manager.yaml
        {{- end }}
        - --logtostderr=true
        - --port={{ .Values.ports.healthcheck }}
        - --v=2
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: etc-kubernetes
          readOnly: true
        {{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        {{- end }}
        livenessProbe:
          httpGet:
            host: 127.0.0.1
            path: /healthz
            port: {{ .Values.ports.healthcheck }}
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 15
      volumes:
      - hostPath:
          path: /etc/kubernetes
        name: etc-kubernetes
